apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tharun-go-web-app
  region: us-east-1

managedNodeGroups:
  - name: app-nodes
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2