apiVersion: v1
kind: Service
metadata:
  name: tharun-go-web-app
  labels:
    app: tharun-go-web-app
spec:
  type: ClusterIP
  selector:
    app: tharun-go-web-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP